exllamav2/exllamav2_ext/cuda/q_gemm.cu

Hit a compiling issue when running the model with Rocm.
```
Traceback (most recent call last):
File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1900, in _run_ninja_build
subprocess.run(
File "/opt/conda/envs/py_3.9/lib/python3.9/subprocess.py", line 528, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v', '-j', '8']' returned non-zero exit status 1.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/var/lib/jenkins/text-generation-webui/repositories/exllamav2/test_inference.py", line 2, in <module>
from exllamav2 import(
File "/var/lib/jenkins/text-generation-webui/repositories/exllamav2/exllamav2/__init__.py", line 3, in …
```

Fix Compiling with HIP on Older Pytorch Version

---

conversion/quantize.py

Currently too much memory is being held in cache by the quantisation implementation, leading to memory being overcommitted; this i.e. breaks quantisation on 4090 GPUs.
While this may possibly make the quantisation slightly slower due to more frequent cache evictions, this made it possible for me to quantise the recently released spicyborous 70B without any issues on a single-4090 rack.
My understanding of this project is to make very-large LMs work on consumer hardware, hence this PR.
Regards

Conversion: release CUDA cache after VRAM intensive quant blocks

---

exllamav2/exllamav2_ext/cuda/q_matrix.cu

If I'm not mistaken, each `reconstruct_gptq_kernel` thread reconstructs 4-columns, so it suffices to use fewer blocks.

Grid number of GPTQ matrix reconstruction

---

.github/workflows/build-wheels-release-rocm.yml
.github/workflows/build-wheels-release.yml
.github/workflows/build-wheels-rocm.yml
.github/workflows/build-wheels.yml
.gitignore
exllamav2/ext.py
setup.py

Resolves: https://github.com/turboderp/exllamav2/issues/56
---
This makes JIT compiling optional and can be opted into by setting the `EXLLAMA_NOCOMPILE` environment variable on install.
This also includes 2 workflows:
- `build-wheels.yml`
- This workflow will build wheels and sdist and upload them as workflow artifacts.
- Useful for testing as you don't need to worry about overwriting working wheels with broken ones.
- Calls `build-wheels-rocm.yml` to build ROCm wheels at the end.
- `build-wheels-release.yml`
- This workflow will do the same as the first and will also upload them to GitHub releases that it will create if needed.
- Parses `setup.py` to determine package version that it will then use as the release tag to upload to.
- Currently configured to overwrite wheels already …

Build wheels with pre-compiled CUDA kernels

---

README.md
examples/chatcode.py

Colored code in the CLI chat!
This PR focuses around the implementation of real-time streaming codeblocks with the `examples/chatcode.py` CLI chat script. Via pyterm, I stream the codeblocks as floating boxes with black background, similar to the ChatGPT interface.
This makes debugging code models much more pleasing :)

Code highlighting in chat CLI

---

exllamav2/generator/speculative.py

Hey! Just wanted to test the `speculative.py` example and noticed that the speculative generator did not use the (I suppose new) sampler syntax, so this is the fix for that. ^^
```py
token, prob = ExLlamaV2Sampler.sample(logits, draft_settings, past, randoms[i])
token, prob, _ = ExLlamaV2Sampler.sample(logits, draft_settings, past, randoms[i], self.tokenizer)
```

Fixed Speculative Generator

---

exllamav2/attn.py

This should solve the error
```
File "/miniconda3/envs/textgen/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 47, in _flash_attn_forward
out, q, k, v, out_padded, softmax_lse, S_dmask, rng_state = flash_attn_cuda.fwd(
RuntimeError: FlashAttention only supports Ampere GPUs or newer.
```
that happens while trying to generate text if you have flash-attn installed (through a wheel) but do not have a compatible GPU.

Check if Ampere GPUs or newer before using flash-attn

---

examples/chat_prompts.py

Hey :) I added the Zephyr chatformat. (despite `encode special tokens` being true, it somehow generated the `<|user|>` token and outputted it in the chat? I hope this has nothing to do with the model being wrongly trained like the TinyLlama one)
Here is a 3.0bpw version to test (if you haven't already quantized it yourself)
https://huggingface.co/SinanAkkoyun/zephyr-7b-alpha-quantized

Added zephyr chatformat

---

.github/workflows/build-wheels-release-rocm.yml
.github/workflows/build-wheels-release.yml
.github/workflows/build-wheels-rocm.yml
.github/workflows/build-wheels.yml

For most systems, the wheels built on Pytorch 2.0.1 work fine with 2.1.
However, for unknown reasons, some systems seem to not work at all unless the wheel is built with Pytorch 2.1.
This PR changes the workflows to use the official Pytorch 2.1 release with CUDA 11.8+ and ROCm.
It also adds some basic error correction as I noticed that Mamba will not always report an error and stop the workflow if CUDA Toolkit fails to install.
I also commented out the PyPI upload functionality for non-sdist builds for convenience as it can't be used at the moment.
Should now only try to upload the JIT-compile wheel and the sdist itself.
I added a comment on line 179 detailing how to only upload the wheel and can add that change to this PR if you want.
Additionally, I made the following changes to the …

Use Pytorch 2.1 for CUDA 11.8+ and ROCm builds

---

exllamav2/model_init.py
exllamav2/tokenizer.py

Add logic to decide use huggingface tokenizer or sentence piece tokenizer.
It can support models using huggingface tokenizer like Falcon and Deepseek Coder

Add Huggingface tokenzier support

---

exllamav2/tokenizer.py

Otherwise, `json` sometimes fails to parse the contents e.g.
```
File "E:\exllamav2_ui\exllamav2\model_init.py", line 101, in init
tokenizer = ExLlamaV2Tokenizer(config)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\exllamav2_ui\exllamav2\tokenizer.py", line 77, in __init__
tokenizer_json = json.load(f)
^^^^^^^^^^^^
File "C:\Program Files\Python311\Lib\json\__init__.py", line 293, in load
return loads(fp.read(),
^^^^^^^^^
UnicodeDecodeError: 'cp932' codec can't decode byte 0x81 in position 812: illegal multibyte sequence
```
Not sure if this could be necessary anywhere else, didn't have any other files fail to load.

Load models' tokenizer.json file with utf-8 encoding.

---

conversion/quantize.py
convert.py
exllamav2/config.py
exllamav2/lora.py
exllamav2/tokenizer.py
setup.py
util/shard.py

Fixes the following error due to Windows quirks. Read the commit message for details
```
Traceback (most recent call last):
File "F:\AI\exllamav2\convert.py", line 100, in <module>
tokenizer = ExLlamaV2Tokenizer(config)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\AI\exllamav2\exllamav2\tokenizer.py", line 77, in __init__
tokenizer_json = json.load(f)
^^^^^^^^^^^^
File "C:\bin\miniconda3\Lib\json\__init__.py", line 293, in load
return loads(fp.read(),
^^^^^^^^^
File "C:\bin\miniconda3\Lib\encodings\cp1252.py", line 23, in decode
return codecs.charmap_decode(input,self.errors,decoding_table)[0]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 735: character maps to <undefined>
```

Fix Unicode errors when loading files

---

examples/chat.py

When setting a custom rope scale, now the `chat.py` example also sets the same rope scale for the draft model (needed for deepseek drafting)

Added draft model rope scale to chat example

---

examples/chat.py
examples/inference.py
examples/lora.py
examples/speculative.py
examples/streaming.py
exllamav2/exllamav2_ext/cpp/sampling.cpp
exllamav2/exllamav2_ext/cpp/sampling.h
exllamav2/exllamav2_ext/ext.cpp
exllamav2/generator/sampler.py
exllamav2/server/websocket_actions.py
tests/test.py

This PR adds support for Top-A sampling (invented by BlinkDL from the RWKV team). Based on the min_p implementation here, since min_p is just linear top_a.

feat: add top-A sampling

---

exllamav2/lora.py

QKV embeddings no longer exist in config, so this assertion will always fire due to config having QKV as None.

Loras: Remove qkv assertion

---

exllamav2/server/websocket_actions.py

I might be misunderstanding something here, but [this code](https://github.com/turboderp/exllamav2/blob/3b0f5230e9619fc0ddf1f302785049d10a65fe26/exllamav2/server/websocket_actions.py#L152) in `websocket_actions.py`:
```python
if "bann_bann" in request:
bb = request["bann_bann"]
if not isinstance(bb, list): bb = [bb]
else:
bb = None
```
Combined with this code that follows:
```python
gs = ExLlamaV2Sampler.Settings()
gs.disallow_tokens(server.tokenizer, bb)
```
Means that we may be passing `None` to `disallow_tokens`, which looks like [this](https://github.com/turboderp/exllamav2/blob/3b0f5230e9619fc0ddf1f302785049d10a65fe26/exllamav2/generator/sampler.py#L83C9-L83C9):
```py
def disallow_tokens(self, tokenizer, tokens):
if self.token_bias is None:
padding = -tokenizer.config.vocab_size % 32 …
```

Fix case where there are no disallowed tokens in `websocket_actions.py`

---

exllamav2/exllamav2_ext/cpp/safetensors.cpp

Resolved specific compiler warnings in safetensors.cpp related to type mismatch and unused variables.
Type Mismatch in Comparisons: Ensured consistent typing by using static_cast to match the signedness of integers during comparisons to resolve warnings for:
Comparison between int and size_t in get_cache_page function.
Comparison between ssize_t and size_t in the check TORCH_CHECK(bytes_read == read_lens[i], "Async read error (2)");.
Unused Variables: Commented out the unused variable file_c in the STFile::load function to eliminate the -Wunused-variable warning.
Rebuilt everything after, warnings gone, inference and functionality seem to work per the usual.

Resolved compiler Warnings for typecasting for proper byte reading and comparison

---

conversion/measure.py
conversion/quantize.py
convert.py

A few user experience enhancements during the quantization and measurement process:
1. Graceful Exit Signal Handling:
- Adds signal handling to allow the measurement process of quantization to exit gracefully. This ensures that the process can be safely paused or stopped, and provides a catch / second chance if a user hits CTRL-C unintentionally.
2. Status Box with useful insights:
- Implements a status box that appears after each measurement process completes of a module in the step-process that provides valuable insights during the quantization process. Most useful is probably the overall accuracy of the quantization and measurement process at that precise moment in time, and a time estimate for completion of the full quant.
Stats in the status box include:
- Rolling average time per …

Add graceful exit sig handling and status box for quantization to assist estimating completion time and overall accuracy

---

exllamav2/generator/streaming.py

Optionally return logits in streaming generator.
I'm trying to make an OpenAI-compatible LLM Server. This is about top_logprobs.
ExLlamaV2StreamingGenerator now optionally returns the probability of the chosen token, but I need the probabilities of the top N candidates. This seemed like the simplest way to get them.

Optionally return logits from streaming generator

---

exllamav2/tokenizer.py

This is an enhancement to fix functionality of Lollms-webui, specifically the lord of internet and wikipedia personalities, as well as anything else that uses workflows or returns list of tensors to be decoded. 
This change identifies the type, and decodes based on the type. If a list is detected it calls itself recursively and decodes each item in the list until completion. 
https://github.com/ParisNeo/lollms-webui/issues/480

Update tokenizer.py to decode list of tensors as well as single tensor

---

examples/chat.py
exllamav2/exllamav2_ext/cpp/sampling.cpp
exllamav2/exllamav2_ext/cpp/sampling.h
exllamav2/exllamav2_ext/ext.cpp
exllamav2/generator/sampler.py

Kalomaze's Quadratic Sampling

---

exllamav2/generator/base.py
exllamav2/generator/filters/select.py

Ran into two bugs trying to use the `Select` filter:
1. The sampler passes "None" as the prefix argument to `begin` when there's no healed token. This was causing an exception because Select expects the prefix to be a string.
2. The generator was ignoring the `end_filter` return value from the sampler, causing it to keep generating even after matching an end token from the `Select` filter. The result is that the Select filter returns an empty `pass_tokens` set on the next call to `next`, causing an exception.
This fixes the first by setting the prefix to the empty string if it's None, and the second by using the `end_filter` return value from the sampler as the default value for the `eos` variable in the generator, which tells the generator it's hit the eos token.
Only tested with …

Fix a couple of filter bugs

---

README.md
examples/chat.py
test_inference.py

There was a missing `pip install -r requirements.txt` step on the installation steps on main page.
This PR adds it with some additional comments/reminders about conda environment (not necessary but potentially useful).
In addition, added some info for people that want to load models on multiple-GPUs.

Fix installation step (install requirements) & Add multi-GPU explanation

---

.github/workflows/build-wheels-release.yml

I haven't actually tested this (I think I would need credentials), but the other workflows are running on Ubuntu 20.04 so I think it'll work.
See #338 for details. 20.04 should be compatible with 22.04 and any newer distributions for a good while.
Docs on GitHub runners: https://docs.github.com/en/actions/using-jobs/choosing-the-runner-for-a-job#choosing-github-hosted-runners

Build on Ubuntu 20.04 for releases

---

util/convert_safetensors.py

This change fixes converting with *.bin from docker command while maintaining the existing functionality for wildcards from command line and lists of files as well
If you want me to remove all the changes my linter made I can fix that, just lemme know

Fix for converting to safetensor with wildcards

---

exllamav2/config.py

This update provides a convenient way to grab `generator_config` properties from `ExLlamaV2Config`, specifically the `eos_token_id` attribute.
Llama-3-instruct models provide `generator_config.json` which contains `eos_token_id` as a list of token IDs accounting for `<|end_of_text|>` and `<|eot_id|>` as stop tokens. The `tokenizer.eos_token_id` typically contains just the end of sequence token and not end of chat token. Llama-3 `generator_config.json` started incorporating both token ids into its config to make adding stop tokens easier.
https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/blob/main/generation_config.json

Load generation_config.json from compatible models

---

examples/cfg.py
exllamav2/attn.py
exllamav2/config.py
exllamav2/model.py
exllamav2/model_init.py

integrate xformers memory_efficient_attention, could be beneficial if your device's architecture is less than <sm_80
The efficiency between xformers.memory_efficient_attention and flash_attn in >sm_80 are almost the same. 
But xformer does not expand the kv automatically, we need to do it manually, and the martix operation make this implemention much slower. 
So the open logic is, try using flash_attn first and then try using xformer and then using Torch matmul attention.

integrate xformers

---

conversion/measure.py
conversion/quantize.py
convert.py

Give user the option to offload hidden/target layers to GPU for speed-up. For the 70B case, I OOM'd at 70 layers. At 60 layers it used the 2nd GPU occasionally ("!! Out of memory (H), moving to device 1"), i.e. you will need more than 24 GB VRAM to do 60 layer offloading if you are doing 8192 context size.
This includes the move of `.item()` commit from #455. Simpler than #456, but has a constant VRAM overhead. It defaults to 0 offloading though, so if people don't touch it, nothing should change.
```
8B model, -l 4096 -ml 4096 -r 100 -mr 100, -hsol 0
--------------------------------------------
| Measured: model.layers.0 (Attention)     |
| Duration: 49.56 seconds                  |
| Completed step: 1/67                     |
| Avg time / step (rolling): 49.56 seconds |
| Estimated …
```

add layer GPU offloading for hidden/target states

---

exllamav2/embedding.py
exllamav2/linear.py
exllamav2/lora.py

Sometimes user when finetuning lora, make `embed_tokens` and `lm_head` trainable and even change the size of vocabulary. I'm making sure that modules in lora is still usable even as lora. But, I'm not sure if there are multiple lora, how to do it. I assume only the first lora is used for `embed_tokens` and `lm_head`

make `embed_tokens` and `lm_head` in lora usable

---

exllamav2/config.py

Add `longrope` alias for Phi-3 mini EXL2 quantization
Fixes [https://github.com/turboderp/exllamav2/issues/537](https://github.com/turboderp/exllamav2/issues/537)

Fix Phi-3 mini new longrope EXL2 quantization

---

doc/dynamic.md

This makes the example work.
I have no idea why github added an edit to the last line with the cat, since I didn't touch that line. I can't even see the edit it made.

Remove stray ) in code example

---

exllamav2/generator/dynamic_async.py

If an async job is cancelled, tell the job to stop generating instead of waiting forever.
~~I'm not sure if the cancel event should raise something, but I put it as a simple break like how an EOS would work. Maybe this should be changed.~~
The correct way to terminate an iterator is to break it. This is done with `__anext__` via `StopAsyncIteration`, but that's not used for this generator.

Fix async job cancellation

---

.github/workflows/build-wheels-release.yml

Add pytorch 2.4.0 wheel support. Remove older versions of ROCm since the newer version supersedes all older ones.

Actions: Add pytorch 2.4.0 to build

---

README.md
exllamav2/ext.py

Without this exllamav2 can't even be imported on a system without GPU:
```
...python3.11/site-packages/exllamav2/ext.py:43: in maybe_set_arch_list_env
arch_list[-1] += '+PTX'
E   IndexError: list index out of range
```

Fix in ext.py (index error on system without GPU)

---

exllamav2/lora.py

If an adapter is trained with RSLoRA, the alpha value is multiplied by `sqrt(rank)`.

fix: support for Rank Stabilized LoRA (RSLoRA)

---

exllamav2/config.py
exllamav2/device.py

As described here:
https://huggingface.co/Qwen/Qwen2.5-32B-Instruct#processing-long-texts
I adapted transformer's YaRN implementation. Note you _must_ manually add this to the model config for the YaRN scaling to kick in!
```json
{
...,
"rope_scaling": {
"factor": 4.0,
"original_max_position_embeddings": 32768,
"type": "yarn"
}
}
```
Relevant issue: https://github.com/turboderp/exllamav2/issues/641
Seems to work in exui and Qwen 2.5 32B Instruct, trying it with: https://huggingface.co/DrNicefellow/Qwen2.5-32B-Instruct-4.25bpw-exl2
It repeats like crazy at 80K context without this PR, and seems quite coherent with it, but consider this a WIP testing PR! I'm just an end user.

Add YaRN scaling for Qwen 2.5

---

eval/humaneval.py

1. Fix the temperature argument to accept values passed via the cmd line.
2. Add more arguments (top_k, top_p, token_repetition_penalty) to accept values passed via the cmd line.

Add more args to humaneval

---

.github/workflows/build-temp.yml
exllamav2/generator/dynamic.py

If `deallocate_pages` is called on a job for which `allocate_pages` has not been called (see `iterate_start_jobs` for conditions under which this is true), `allocated_pages` is `None`, raising a NPE when attempting to iterate.
In particular, this prevents `clear_queue` from working. In practice, this problem readily occurs when starting a few jobs and then calling `clear_queue`.

Prevent NPE in `deallocate_pages`

---

exllamav2/rope.py

When loading a model with yarn or su scaling, `scaling_factor` is left unbound when the requested `max_seq_len` <= the model's original unscaled `max_seq_len`, resulting in an UnboundLocalError.
For example when loading a Qwen2 Instruct model with the suggested yarn settings:
```json
{
...,
"rope_scaling": {
"factor": 4.0,
"original_max_position_embeddings": 32768,
"type": "yarn"
}
}
```
and subsequently loading the model with a `max_seq_len` of 32768 or less.

Prevent UnboundLocalError when loading with yarn/su with short ctx len

---

exllamav2/architecture.py
exllamav2/config.py
exllamav2/vlm/mmprojector.py

Read multimodal_projector_bias from model config with fallback to True if not present, read hidden_size from model config and fallback to 1024 if not present.
This and the other changes in dev branch should make Pixtral Large work well without breaking support for Pixtral 12B.

Modify handling for Pixtral Large model params

---

exllamav2/tensor_p.py

Since 7b05acd233cc467e19690e9434f3464a7a633e33, sin and cos in the device context are split by layer. However, the external functions `tp_attn_forward_` and `tp_attn_forward_paged_` expect a single tensor per device. I've changed the `get_sin_cos` method of the `TPContext` class to concatenate these tensors before providing them to the external functions.
The error message I was receiving before making this change was:
```
TypeError: tp_attn_forward_(): incompatible function arguments. The following argument types are supported:
1. (arg0: int, arg1: torch.Tensor, arg2: list[torch.Tensor], arg3: list[torch.Tensor], arg4: list[torch.Tensor], arg5: list[torch.Tensor], arg6: list[torch.Tensor], arg7: list[torch.Tensor], arg8: list[torch.Tensor], arg9: list[torch.Tensor], arg10: …
```

Fix for tensor parallelism with newly split sin/cos tensors

---

exllamav2/config.py
exllamav2/generator/dynamic.py

As per a new change in the transformers/huggingface, where they eliminated the "Qwen2_5_VLImageProcessor" type, because it was the same preprocessing as "Qwen2VLImageProcessor" due to the similar architecture, the huggingface models for Qwen2.5_VL come with "Qwen2VLImageProcessor" instead of "Qwen2_5_VLImageProcessor". 
This has resulted in a problem where the same model from huggingface cannot be used with both transformers and exllamav2 at the same time. And you have to manually edit the file to fix this when switching between frameworks.. I can't override the config either at any point through the code easily, as the code is not designed in this way (in exllamav2). 
This PR simply adjusts the check to allow for both "Qwen2_5_VLImageProcessor" and "Qwen2VLImageProcessor".
I don't think …

Added Fix for Loading unquantized Huggingface models.
